- hosts: workstation
  become: true
  roles:
    - system
    - db_servers
    - monitoring
    - web_servers
  vars:
    server_users:
      - name: "ash"
        password: "imnotarobot"
        group: "sudo"
        groups:
          - "developers"    