---
# defaults file for roles/exporters
node_exporter_version: 1.5.0
node_exporter_web_listen_address: '0.0.0.0:9100'

node_exporter_textfile_dir: '/var/lib/node_exporter'

node_exporter_enabled_collectors:
  - systemd
  - textfile:
      directory: '{{ node_exporter_textfile_dir }}'
  - diskstats:
      ignored-devices: '^(ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\\d+n\\d+p)\\d+$'
  - filesystem:
      ignored-mount-points: '^/(sys|proc|dev|run)($|/)'
  - netdev:
      device-exclude: '^lo$'

mysqld_exporter_version: 0.14.0
mysqld_exporter_web_listen_address: '0.0.0.0:9104'

mysqld_exporter_enabled_collectors:
  - binlog_size
  - auto_increment.columns
  - engine_innodb_status
  - engine_tokudb_status
  - info_schema.schemastats
  - slave_status

_mysqld_exporter_db_user: exporter

_exporter_binary_install_dir: '/usr/local/bin'
_exporter_system_user: prometheus
_exporter_system_group: adm

# vars file for roles/exporters
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

go_arch: '{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}'