- name: Create mysqld_exporter User Config
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/.exporter.cnf
    mode: 0600
    owner: '{{ _exporter_system_user }}'
    group: '{{ _exporter_system_group }}'
  notify: restart mysqld_exporter

- name: Setup mysqld_exporter Service
  ansible.builtin.template:
    src: mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart mysqld_exporter

- name: Copy mysqld_exporter Config
  ansible.builtin.template:
    src: mysqld_exporter.j2
    dest: /etc/default/mysqld_exporter
    owner: root
    group: root
    mode: 0644
  notify: restart mysqld_exporter

- name: Setup mysqld_exporter User
  community.mysql.mysql_user:
    name: '{{ _mysqld_exporter_db_user }}'
    password: '{{ _mysqld_exporter_db_password }}'
    # config_file: /etc/.exporter.cnf
    state: present
    priv: '*.*:SELECT,PROCESS,REPLICATION CLIENT'
  become: true
  tags: mysqld_exporter  