---
# tasks file for roles/exporters
- import_tasks: preflight.yml
  tags: mysqld_exporter

- import_tasks: node_exporter.yml
  become: true

- import_tasks: mysqld_exporter.yml
  become: true

- import_tasks: configure_node_exporter.yml
  become: true

- import_tasks: configure_mysqld_exporter.yml
  become: true  