- name: Install MySQL 8 (Ubuntu)
  apt:
    name:
      - mysql-server
      - libmysqlclient-dev
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'
  notify: start_enable_mysql

- name: Setup repo for Mysql 8.0 (RHEL/CentOS)
  yum:
    name: http://repo.mysql.com/mysql57-community-release-el7-10.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat'  
  
- name: Install MySQL 8 (RHEL/CentOS)
  yum:
    name:
      - mysql-server
      - mysql-devel
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  notify: start_enable_mysql
  
- name: Install Redis
  apt:
    name: redis-server
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'
  notify: start_enable_redis
  
- name: Install Redis (RHEL/CentOS)
  yum:
    name: redis
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  notify: start_enable_redis