- name: Install MySQL 8 (Ubuntu)
  apt:
    name:
      - mysql-server
      - libmysqlclient-dev
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'
  notify: start_enable_mysql

- name: DEBIAN | Configure MySQL
  ansible.builtin.template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: 0
    group: 0
    mode: 0640
    validate: mysqld --defaults-file=%s --validate-config
    force: true
  notify: start_enable_mysql
  when: ansible_os_family == "Debian"  

- name: Setup my.cnf file for root
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    backup: true
    force: false
    mode: 0600
    owner: 0
    group: 0
  register: my_cnf
  become: true

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present  

- name: Setting up root credentials
  mysql_user:
    name: root
    password: "{{ _mysql_db_password }}"
    login_user: root
    login_password: "{{ _mysql_db_password }}"
    host: localhost
    login_unix_socket: /var/lib/mysql/mysql.sock
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true 
    state: present
  become: true  